name=AmAlert
version=1.0.0
author=ArtronShop CO.,LTD.
maintainer=Sonthaya Nongnuch <sonthaya.nt@hotmail.com>
sentence=Am Alert library for ESP32, ESP8266 and Arduino Uno R4 WiFi
paragraph=Send notification message and images to Am Alert service
category=Communication
url=https://github.com/ArtronShop/AmAlert-Arduino
architectures=*
includes=AmAlert.h
